# Quick start:
# $ docker compose -f compose.talker.yaml up

services:
  talker:
    build: .
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=123
      - WIFI_DEV_NAME=wlp0s20f3
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
    command: ros2 run demo_nodes_cpp talker