# Quick start:
# $ docker compose -f compose.talker.yaml up

services:
  talker:
    build: .
    tty: true 
    network_mode: host
    ipc: host
    restart: always
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: rosrun rospy_tutorials talker.py

  listener:
    build: .
    tty: true 
    network_mode: host
    ipc: host
    restart: always
    environment:
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311
    command: rosrun rospy_tutorials listener.py

  ros_master:
    image: ros:noetic-ros-core
    tty: true 
    network_mode: host
    ipc: host
    restart: always
    environment:
      - ROS_IP=127.0.0.1
    command: roscore